---
- name: "VMs aus vCenter abrufen"
  import_tasks: vms_hinzufuegen.yml

- name: "IP-Adressen hinzufügen"
  import_tasks: ip_adressen_hinzufuegen.yml 
    
- name: "Schnittstellen anlegen"
  import_tasks:  schnittstellen_create.yml

- name: "Schnitstellen mit IPs linken"
  import_tasks: schnittstellen_linken.yml

- name: "Status der VMs aktualisieren"
  import_tasks: status_sync.yml

- name: "Cleanup VMs, Ips, Interfaces"
  import_tasks: cleanup.yml
