---
- name: "Hole VM-Objekt aus NetBox anhand des VM-Namens"
  uri:
    url: "{{ netbox_url }}/api/virtualization/virtual-machines/?name={{ item.guest_name | urlencode }}"
    method: GET
    headers:
      Content-Type: "application/json"
      Authorization: "Token {{ netbox_api_token }}"
    return_content: yes
    status_code: [200]
    validate_certs: no
  register: nb_vm_info
  loop: "{{ vcenter_vms.virtual_machines }}"
  loop_control:
    label: "{{ item.guest_name }}"

- name: "Aktualisiere den Status der VMs in NetBox"
  uri:
    url: "{{ netbox_url }}/api/virtualization/virtual-machines/{{ item.json.results[0].id }}/"
    method: PATCH
    headers:
      Content-Type: "application/json"
      Authorization: "Token {{ netbox_api_token }}"
    body_format: json
    body: >-
      {
         "status": "{{ 'active' if item.item.power_state == 'poweredOn' else 'offline' }}"
      }
    status_code: [200]
    validate_certs: no
  loop: "{{ nb_vm_info.results }}"
  loop_control:
    label: "{{ item.item.guest_name }}"
  when: (item.json.results | length > 0)

