---
- name: "Hole alle VMs aus vCenter"
  community.vmware.vmware_vm_info:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
  register: vcenter_vms

- name: "VMs in NetBox eintragen"
  uri:
    url: "{{ netbox_url }}/api/virtualization/virtual-machines/"
    method: POST
    headers:
      Content-Type: "application/json"
      Authorization: "Token {{ netbox_api_token }}"
    body_format: json
    body: >-
      {
        "name": "{{ item.guest_name }}",
        "status": "active",
        "cluster": {"name": "{{ netbox_cluster }}"},
        "site": {"name": "{{ netbox_site }}"}
      }
    validate_certs: no
  loop: "{{ vcenter_vms.virtual_machines }}"
  register: netbox_vm_result
  ignore_errors: yes

- name: "Überprüfe Statuscode der API-Anfrage"
  debug:
    msg: "VM erfolgreich hinzugefügt: {{ item }}"
  loop: "{{ netbox_vm_result.results }}"
  when: item.status | default(0) in [200, 201]

